### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by LucasVanni** [erickriva/git-watch-vscode-rename#1]
ERROR MESSAGE:
fatal: not under version control, source=src/services/webflow.ts, destination=src/services/guykbsb102cz1iq60adre.ts

**Comment by ctf0** [comment]
same here

**Comment by erickriva** [comment]
When file hasn't been added to Git yet (with `git add`), renaming it should make Git work fine. This extension is not intended to work in this case.
I'm not sure there's a validation I can do to avoid this error from appearing 🤔. Will look into it.

**Comment by erickriva** [comment]
New version released. This error shouldn't appear anymore.
Closing issue for now.
