### ISSUE TITLE
Renaming a folder 

### ISSUE THREAD

**Issue by theking2** [erickriva/git-watch-vscode-rename#3]
Renaming a folder does not trigger git-mv it is just tracked as a delete/add:
![image](https://user-images.githubusercontent.com/1612152/225382375-fa37e6cc-66e8-4c9d-9048-0b841a08505a.png)

**Comment by erickriva** [comment]
There is a specific case Git can't deal: changing case only.
You can commit, but another machine that already has this project with old filename won't recognize the name changes to be made to these files.

`Administration` being renamed to `administration` can't be tracked by Git, at least for Windows and MacOS. Linux seems to be working fine.
`Administration` being renamed to `_Administration` works fine, so this extension won't execute `git-mv`.

This being aligned, do you think there is still some unexpected behavior in this case?

**Comment by theking2** [comment]
I did rename the folder from `Administration` to `_Administration` and hoped it would trigger a git-mv. But it didn't.

**Comment by erickriva** [comment]
But it won't. It is not needed. VSCode and Git already do this work nicely.
Can you share which type of problems are you trying to solve with this `git-mv`?

**Comment by theking2** [comment]
Renaming a folder verbatim result in its content being deleted and re-added. This is the result of a rename of folder `src` to `src_`:
```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    src/DBPersistTrait.trait.php

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        src_/

no changes added to commit (use "git add" and/or "git commit -a")
```

so, no, vscode does not report git-mv.
